### ISSUE TITLE
loading by key broken?

### ISSUE THREAD

**Issue by ccurry21** [gtri/typesafeconfig-extensions#12]
```
        config = ConfigFactory.withSources(
                    classpathResource("someInitialConfig"),
                    configFile().byKey("app.config.file")
            ).fromLowestToHighestPrecedence().load();
```

Try loading an external config file with -Dapp.config.file=./path/somefile when launching the app. The properties in ./path/somefile.conf seem to be ignored.  However, the following will work:

```
        config = ConfigFactory.withSources(
                    classpathResource("someInitialConfig"),
                    configFile().byPath(Paths.get(System.getProperty("app.config.file")))
            ).fromLowestToHighestPrecedence().load();
```

**Comment by chris-martin** [comment]
Hey, sorry I didn't notice this issue because I'm not a part of this organization anymore (no one is, so this project is unmaintained, though I might fork it myself if necessary).

`ConfigFactory` is built _completely_ from scratch - it won't use any sources that you don't explicitly add. You need to include `.withSources(systemProperties())` to include the system properties source - Otherwise system properties will have absolutely no effect.

(So I don't think this is a bug.)

**Comment by jokajak** [comment]
I agree with chris-martin that this is not a bug.
